env:
  browser: true
  es6: true
extends: ['plugin:react/recommended']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - import
rules: {
  'quotes': ['error', 'single'],
  'no-unused-vars': ['warn'],
}
